### PR TITLE
Landing Markers

### PR DESCRIPTION
**Pull request by Duzos**
enhancement #193

### CODE REVIEW

**Comment by Duzos** [comment]
@Loqor

**Comment by Loqor** [comment]
- [ ] GUI for the zones, accessible by right-clicking the block
- [ ] "Landing permission code"
- [ ] Repellent zones
- [ ] Configurable size within a chunk

**Comment by Duzos** [comment]
edit the message and split those four into more detailed sub checkboxes like

GUI
- [ ] blah
- [ ] bluh

Permission Code
- [ ] sigma
- [ ] rizz

etc

**Comment by Duzos** [comment]
todo before ready for merge:
- improved GUI for landing codes

**Pull request merged**
