### PR TITLE
TARDIS Experamental Warning

### PR DESCRIPTION
**Pull request by MaketendoDev**
i cooked with my lang files
image
image

### CODE REVIEW

**Comment by SpartanGamezFTB** [comment]
this is neat but its spelt "Gallifreyan" just to help out :)

**Comment by MaketendoDev** [comment]
fudge i did it again

**Comment by MaketendoDev** [comment]
fixed

**Comment by Duzos** [comment]
its "Transdimensional"

**Comment by MaketendoDev** [comment]
shush

> its "Transdimensional"

i didn't even spell it wrong :skull:

**Comment by Duzos** [comment]
right..
image

**Comment by MaketendoDev** [comment]
image

**Comment by MaketendoDev** [comment]
> right.. image

i think thats an old photo
no idea why its that

**Comment by MaketendoDev** [comment]
ok

**Comment by MaketendoDev** [comment]
image
 ok

**Comment by MaketendoDev** [comment]
no idea why i brung that up

**Comment by Duzos** [comment]
the file should be called "en_us.existing.json"

**Comment by MaketendoDev** [comment]
> the file should be called "en_us.existing.json"

oh ok

**Comment by MaketendoDev** [comment]
done

**Pull request merged**
