### PR TITLE
Create 2024-3-10-TARDIS-Secutity.md

### PR DESCRIPTION
**Pull request by MaketendoDev**
Updated Iphometic (ik i spelt it wrong) Security to just TARDIS Security

### CODE REVIEW

**Comment by Duzos** [comment]
LGTM

**Comment by Duzos** [comment]
You need to add more newlines between the image and the text 
image

**Comment by MaketendoDev** [comment]
---
layout: post
comments: true
categories: ["Specifics"]
---
# TARDIS Security Features
Feel like locking the door isn't enough? No worries as if you go into your [**Console**]({{ site.baseurl }}{% post_url 2024-02-02-tardis-console %}) then hit **Settings** above the **Sonic Settings** you should see the **Security** button. Right clicking the button takes you to this menu...

Security Menu
Here you can see when your TARDIS has been build and you can change some security settings.

## Leave Behind
When activating this feature any other guest that doesn't have a **TARDIS key** (that is linked to your TARDIS) should leave the person behind when taking off your TARDIS. This feature is inspired by the Doctor WHO episode "Blink"

## Hostile Alarms
When this feature has been activated any hostile mobs that entered the **TARDIS** triggers the **Cloister Bell** until you have manually turned it off

# Other Info
# How to activate Isomorphic Security (Protocol 19)
On the console, find "Protocol 19" and use a key linked to that TARDIS and click on the control. Once that's done, anyone that has a key that's linked to the current TARDIS can use the console, but anyone without cannot interact with it at all.

**Comment by Duzos** [comment]
You also spelt `Secutity` wrong
Its Security.
I should've looked it over more
Create a new PR with the updated stuff please

**Comment by MaketendoDev** [comment]
k

**Pull request merged**
