### PR TITLE
Main Menu Button to Wiki

### PR DESCRIPTION
**Pull request by MaketendoDev**
image
:3

### CODE REVIEW

**Comment by MaketendoDev** [comment]
ofc if you want to change the button go ahead i make terrible buttons

**Comment by MaketendoDev** [comment]
i also used loqors config code since ye didn't added it yet

**Comment by MaketendoDev** [comment]
ah resizing the window breaks it

**Comment by Duzos** [comment]
fix resize issues and it’ll be merged

**Comment by DrTheodor** [comment]
Imho this PR is unnecessary.
The wiki button should be in the modmenu of the mod, no need to change the main menu for no reason.

**Comment by MaketendoDev** [comment]
sure

**Comment by Duzos** [comment]
fairs

**Pull request closed without merging**
